[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "eudemo"
dynamic = ["version"]
description = 'This project contains the EU-DEMO reactor design.'
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = []
authors = [
  { name = "The Bluemira Team", email = "" },
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
]

dependencies = ["bluemira", "numpy", "matplotlib"]

[project.optional-dependencies]
dev = ["pre-commit"]
test = [
  "pytest",
  "coverage[toml]",
  "pytest-html",
  "pytest-metadata",
  "pytest-json-report",
]
docs = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
  "mkdocs-gen-files",
  "mkdocs-section-index",
  "mkdocs-literate-nav",
]
lint = ["ruff", "mypy"]

[project.urls]
Documentation = "https://github.com/Fusion-power-plant-framework/bluemira-eudemo#readme"
Issues = "https://github.com/Fusion-power-plant-framework/bluemira-eudemo/issues"
Source = "https://github.com/Fusion-power-plant-framework/bluemira-eudemo"

[tool.hatch.version]
source = "vcs"
[tool.hatch.build.hooks.vcs]
version-file = "eudemo/_version.py"

# env: default
[tool.hatch.envs.default]
features = ["dev", "test", "docs", "lint"]

# env: docs
[tool.hatch.envs.docs]
features = ["docs"]
[tool.hatch.envs.docs.scripts]
build = "mkdocs build"
serve = "mkdocs serve"
deploy = "mkdocs gh-deploy"

# env: lint
[tool.hatch.envs.lint]
detached     = true                           # Don't inherit from default (does not download project dependencies)
dependencies = ["ruff", "mypy", "pre-commit"]
[tool.hatch.envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:eudemo tests}"
style  = ["ruff {args:check .}"]
fmt    = ["pre-commit run --all-files --hook-stage manual"]
all    = ["style", "typing"]

# env: test
[tool.hatch.envs.test]
features = ["test"]
[[tool.hatch.envs.test.matrix]]
python = ["3.10", "3.11", "3.12"]
[tool.hatch.envs.test.scripts]
tests      = "pytest {args:tests}"
tests-cov  = "pytest --cov eudemo  --cov-report html:htmlcov_eudemo --cov-report xml {args:tests}"
tests-cov-private  = "pytest --private --cov eudemo --cov-report html:htmlcov --cov-report xml {args:tests}"

# tool: ruff
[tool.ruff]
line-length = 89
preview = true

[tool.ruff.lint]
exclude = [
  ".git",
  "__pycache__",
  "documentation",
  ".env",
  ".idea",
  ".pytest_cache",
  "htmlcov",
]
select = ["ALL"]
ignore = [
    "D",       # Temporarily ignore
    "N",
    "PLR",
    "TD",
    "DOC",
    "ARG",
    "SLF",
    "ANN",     # type annotations
    "EM",      # string in error messages
    "PD",      # Pandas
    "B019",    # using cache memory leaks
    "COM812",  # enforce trailing comma, disagrees with black/ruff format
    "D107",
    "D200",    # docs stuff
    "D203",
    "D205",
    "D301",
    "D400",
    "D401",
    "DOC502",  # Omit non-explicit exceptions from docstrings
    "DTZ005",  # datetime timezone arg
    "E203",    # black/ruff format conflicts
    "FIX002",  # Line contains todo
    "ISC001",  # ruff format conflict
    "PLW1514", # Specify file open encoding
    "PTH123",  # use Path.open
    "TRY003",  # put error messages in error class
    "FURB152",  # 3.14 != pi
    "PIE790",  # TMP for false positive ...
    "ERA",  # remove commented out code
    "T201",
    "DOC201",
]
unfixable = [
  "F401", # Don't touch unused imports
]

[tool.ruff.lint.isort]
known-first-party = ["eudemo"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**" = ["PLR2004", "S101", "TID252", "D", "N", "PLR", "INP001", "PLC2701"]
"__init__.py" = ["F401", "F403"]
"studies/**/*" = ["INP001", "CPY001"]

[tool.ruff.lint.flake8-copyright]
notice-rgx = "(?i)# SPDX-FileCopyrightText:\\s\\d{4}(-(\\d{4}|present))*"

[tool.coverage.run]
source_pkgs = ["eudemo", "tests"]
branch = true
parallel = true
omit = ["eudemo/_version.py"]

[tool.coverage.paths]
base = ["eudemo", "*/eudemo"]
tests = ["tests", "*/eudemo/tests"]

[tool.coverage.report]
"exclude_also" = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
omit = ["eudemo/_version.py"]

[tool.pytest.ini_options]
testpaths = ["tests"]
